/**
 * @module build_info
 * build_info.js — AUTO-GENERATED. Do not edit by hand.
 * Regenerated by tools/gen_build_info.sh via the pre-commit hook.
 * Build stamp (CalVer date + short hash) and user-facing release notes
 * harvested from commit `Note:` lines (see docs/COMMIT_GUIDE.md).
 */

export const BUILD = {
  date: "2026.07.10",
  hash: "e235c8e",
  count: 271,
  notes: [
    { date: "2026-07-10", hash: "7b2ce0a", text: "New Matte option adds a margin to shots" },
    { date: "2026-07-10", hash: "e901879", text: "About now has clickable links to X and GitHub" },
    { date: "2026-07-10", hash: "d5137b8", text: "A WELCOME window now greets you at startup with what's new" },
  ],
};
