/**
 * @module build_info
 * build_info.js — AUTO-GENERATED. Do not edit by hand.
 * Regenerated by tools/gen_build_info.sh via the pre-commit hook.
 * Build stamp (CalVer date + short hash) and user-facing release notes
 * harvested from commit `Note:` lines (see docs/COMMIT_GUIDE.md).
 */

export const BUILD = {
  date: "2026.07.13",
  hash: "b654ac8",
  count: 299,
  notes: [
    { date: "2026-07-13", hash: "b654ac8", text: "TESSERA no longer opens full-screen" },
    { date: "2026-07-12", hash: "6a8712d", text: "ROLL now has rubber-band note selection" },
    { date: "2026-07-12", hash: "4378124", text: "Roll can now save and open note clips" },
    { date: "2026-07-11", hash: "6699d81", text: "SYNTH: fixed velocity mode (FIX toggle)" },
    { date: "2026-07-11", hash: "b96d3f3", text: "SYNTH gets a wide layout and voice count" },
    { date: "2026-07-11", hash: "217e3d9", text: "MIDI keyboard timing is now steady" },
    { date: "2026-07-11", hash: "15cf8c5", text: "SYNTH ADSR now uses vertical faders" },
    { date: "2026-07-11", hash: "7fd8b89", text: "SYNTH ADSR now uses vertical faders" },
    { date: "2026-07-10", hash: "7b2ce0a", text: "New Matte option adds a margin to shots" },
    { date: "2026-07-10", hash: "e901879", text: "About now has clickable links to X and GitHub" },
    { date: "2026-07-10", hash: "d5137b8", text: "A WELCOME window now greets you at startup with what's new" },
  ],
};
