#!/bin/sh
# gen_build_info.sh — js/build_info.js を git メタデータから生成する。
#
# .githooks/pre-commit から呼ばれる。生成物 (js/build_info.js) はそのまま
# コミット・配信される (GitHub Pages / itch はコミット済みファイルを配信するため)。
#
# 記録内容:
#   date  : 生成日 (CalVer, YYYY.MM.DD)。手動更新不要・常に新鮮。
#   hash  : git の短縮ハッシュ (pre-commit 時は親コミット = "based on")。
#   count : コミット総数 (単調増加)。
#   notes : コミットの `Note:` 行を新しい順に収穫したもの (WELCOME 用)。
#
# 素の checkout (フック未実行) でもアプリが動くよう、失敗しても呼び出し側
# (pre-commit) はコミットを止めない。
set -eu

ROOT=$(git rev-parse --show-toplevel)
OUT="$ROOT/js/build_info.js"

DATE=$(date +%Y.%m.%d)
HASH=$(git rev-parse --short HEAD 2>/dev/null || echo 0000000)
COUNT=$(git rev-list --count HEAD 2>/dev/null || echo 0)

# `Note:` 行を収穫 (新しい順・最大 12 件)。トレーラーブロックの厳密さに依存せず、
# 本文中の行頭 `Note:` を直接拾う (Co-Authored-By との間に空行が入っても拾える)。
# レコード区切り 0x1e / フィールド区切り 0x1f はコミット本文に現れない制御文字。
NOTES=$(git log -n 400 --format='%x1e%h%x1f%cs%x1f%B' 2>/dev/null | awk '
  BEGIN { RS = "\x1e" }
  {
    if (length($0) == 0) next;
    p1 = index($0, "\x1f"); hash = substr($0, 1, p1 - 1); rest = substr($0, p1 + 1);
    p2 = index(rest, "\x1f"); date = substr(rest, 1, p2 - 1); body = substr(rest, p2 + 1);
    n = split(body, lines, "\n");
    for (i = 1; i <= n; i++) {
      ln = lines[i]; sub(/\r$/, "", ln);
      if (ln ~ /^Note:[ \t]*/) {
        note = ln; sub(/^Note:[ \t]*/, "", note);
        gsub(/\\/, "\\\\", note);
        gsub(/"/, "\\\"", note);
        printf "    { date: \"%s\", hash: \"%s\", text: \"%s\" },\n", date, hash, note;
        c++; break;
      }
    }
    if (c >= 12) exit;
  }')

{
  echo "/**"
  echo " * @module build_info"
  echo " * build_info.js — AUTO-GENERATED. Do not edit by hand."
  echo " * Regenerated by tools/gen_build_info.sh via the pre-commit hook."
  echo " * Build stamp (CalVer date + short hash) and user-facing release notes"
  echo " * harvested from commit \`Note:\` lines (see docs/COMMIT_GUIDE.md)."
  echo " */"
  echo ""
  echo "export const BUILD = {"
  echo "  date: \"$DATE\","
  echo "  hash: \"$HASH\","
  echo "  count: $COUNT,"
  echo "  notes: ["
  if [ -n "$NOTES" ]; then printf '%s\n' "$NOTES"; fi
  echo "  ],"
  echo "};"
} > "$OUT"
